---
- block:
    - name: Check if mandatory parameters are correct
      fail:
        msg: "mandatory parameter '{{ item }}' is undefined"
      when: "{{ item }} is undefined"
      with_items:
        - [data_center_name, compatibility_version ]
    
    - name: Check if hosts are correct
      fail:
        msg: "'hosts' variable does not contain mandatory parameter '{{ item[1] }}'"
      when: item[1] not in item[0]
      with_nested:
        - "{{ hosts | default([]) }}"
        - ['name']

    - name: Login to oVirt
      ovirt_auth:
        url: "{{ engine_url | default(omit) }}"
        username: "{{ engine_user | default(omit) }}"
        password: "{{ engine_password | default(omit) }}"
        ca_file: "{{ engine_cafile | default(omit) }}"
        insecure: "{{ engine_insecure | default(true) }}"
      when: ovirt_auth is undefined
      register: loggedin
      tags:
        - always

    - name: Create infrastrucutre
      import_tasks: create_infra.yml
      when: data_center_state == 'present'

    - name: Remove infrastrucutre
      import_tasks: remove_infra.yml
      when: data_center_state == 'absent'

  always:
    - name: Logout from oVirt
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      when: not loggedin.skipped | default(false)
      tags:
        - always
